services:
  - type: web
    name: wa-expense-bot
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: N8N_WEBHOOK_URL
        sync: false   # set this manually in Render dashboard
